// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
import "dotenv/config";

describe('HEOnline_AccountDaten_v2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('HEOnline_AccountDaten_v2', async function() {
    await driver.manage().setTimeouts({ implicit: 2000 });
    await driver.manage().window().setRect({ width: 1302, height: 923 })
    await driver.get("https://heonline.hs-esslingen.de/")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("username")).sendKeys(process.env.loginname.toString())
    await driver.findElement(By.id("password")).sendKeys(process.env.loginpassword.toString())
    await driver.findElement(By.name("_eventId_proceed")).click()
    await driver.findElement(By.css("#co-access-wrapper-co_loc_zug_49332-st .ca-link")).click()
    const iframe = driver.findElement(By.css('iframe'));
    await driver.switchTo().frame(iframe);
    const frame = driver.findElement(By.css('frame'))
    await driver.switchTo().frame(frame)
    const meinNam = await driver.findElement(By.css('tr:nth-child(1) > .detailStd')).getText()
    const meinName = await driver.findElement(By.css('[class="detailStd"]')).getText();
    console.log(meinName)
    console.log(meinNam);
    assert(process.env.loginname.toString() === meinName, "Der Name ist nicht der korrekte Name wie beim Anmelden")
    assert(process.env.loginname.toString()+"@hs-esslingen.de" === meinName+"@hs-esslingen.de", "Die Email-Adresse ist falsch")
  })
})
