// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { WebDriver } = require('selenium-webdriver')
import "dotenv/config";

describe('HEOnline_AccountDaten', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('HEOnline_AccountDaten', async function() {
    await driver.get("https://heonline.hs-esslingen.de/")
    await driver.manage().window().setRect({ width: 1302, height: 923 })
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("username")).sendKeys(process.env.loginname.toString())
    await driver.findElement(By.id("password")).sendKeys(process.env.loginpassword.toString())
    await driver.findElement(By.name("_eventId_proceed")).click()

    //await driver.findElement(By.css("label")).click()
    //await driver.findElement(By.name("_eventId_proceed")).click()
    {
      const element = await driver.findElement(By.id("access-name-co_loc_zug_39138-st"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css("#co-access-wrapper-co_loc_zug_39138-st .ca-link"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css("#co-access-wrapper-studreports_des_stu-st .ca-link"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css("#access-menu-studreports_des_stu-st .mat-mdc-button-touch-target"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css("#co-access-wrapper-studreports_des_stu-st .ca-link-img-container"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("#co-access-wrapper-co_loc_zug_49332-st .ca-icon")).click()
    await driver.switchTo().frame(0)
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("tr:nth-child(1) > .detailStd")).click()
    await driver.findElement(By.css("tr:nth-child(8) > .detailStd")).click()
    await driver.switchTo().defaultContent()
    await driver.switchTo().defaultContent()
    {
      const element = await driver.findElement(By.css("*[data-test=\"id_brm-pm-dtop_navbar_username-label\"]"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
